## Geometry Analysis Project Solution

In [10]:
import numpy
import os

file_location = os.path.join('data', 'water.xyz')
xyz_file = numpy.genfromtxt(fname=file_location, skip_header=2, dtype='unicode')
symbols = xyz_file[:,0]
coordinates = xyz_file[:,1:]
coordinates = coordinates.astype(numpy.float)
num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        if num1<num2:
            x_distance = coordinates[num1,0] - coordinates[num2,0]
            y_distance = coordinates[num1,1] - coordinates[num2,1]
            z_distance = coordinates[num1,2] - coordinates[num2,2]
            bond_length_12 = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
            if bond_length_12 > 0 and bond_length_12 < 1.5:
                print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')
        

O to H1 : 0.969
O to H2 : 0.969


In [11]:
#def function_name(parameters):
#    function code goes
#    this could be multiple lines
#    return value_to_return

In [17]:
def calculate_distance(atom1_coord, atom2_coord):
    """
    This function takes the coodinates of two atoms and calculates the distances between them.
    Inputs: atom1_coord, atom2_coord
    Return: distance
    """
    x_distance = atom1_coord[0]-atom2_coord[0]
    y_distance = atom1_coord[1]-atom2_coord[1]
    z_distance = atom1_coord[2]-atom2_coord[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance

In [18]:
num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        if num1<num2:
            bond_length_12 = calculate_distance(coordinates[num1], coordinates[num2])
            if bond_length_12 > 0 and bond_length_12 < 1.5:
                print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')
        

O to H1 : 0.969
O to H2 : 0.969


In [19]:
help(calculate_distance)

Help on function calculate_distance in module __main__:

calculate_distance(atom1_coord, atom2_coord)
    This function takes the coodinates of two atoms and calculates the distances between them.
    Inputs: atom1_coord, atom2_coord
    Return: distance



In [20]:
#Write a new function called bond_check.  Check and see if a distance is between 0 and 1.5
#angstoms.  Return True or False

def bond_check(distance):
    """
    The function accepts a single distance (one number) and checks to see if it is between 0
    and 1.5.  It returns True or False.
    """
    if distance > 0 and distance < 1.5:
        return True
    else:
        return False

In [21]:
bond_check(4)

False

In [22]:
bond_check(1.2)

True

In [23]:
bond_check(-5)

False

In [24]:
def bond_check(distance, mininum_length, maximum_length):
    """
    The function accepts a single distance (one number) and checks to see if it is between 
    the specificed minimum and maximum values.  It returns True or False.
    """
    if distance > mininum_length and distance < maximum_length:
        return True
    else:
        return False

In [25]:
bond_check(5,0,1.6)

False

In [26]:
bond_check(1.5,0,1.6)

True

In [27]:
def bond_check(distance, mininum_length=0, maximum_length=1.5):
    """
    The function accepts a single distance (one number) and checks to see if it is between 
    the specificed minimum (default: 0 angstroms) and maximum values (default: 1.5 angtroms).  
    """
    if distance > mininum_length and distance < maximum_length:
        return True
    else:
        return False

In [28]:
bond_check(1.5)

False

In [29]:
bond_check(1.5, maximum_length=1.6)

True

In [30]:
num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        if num1<num2:
            bond_length_12 = calculate_distance(coordinates[num1], coordinates[num2])
            if bond_check(bond_length_12) is True:
                print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [31]:
# Write a function that reads in and processes an xyz file.  
# Function name open_xyz
# Input filename
# Two outputs:  symbols and coordinates

def open_xyz(filename):
    """
    Opens and processes a standard format xyz file.  Returns symbols and numpy array
    of coordinates.
    """
    xyz_file = numpy.genfromtxt(fname=filename, skip_header=2, dtype='unicode')
    symbols = xyz_file[:,0]
    coordinates = xyz_file[:,1:]
    coordinates = coordinates.astype(numpy.float)
    return symbols, coordinates

In [32]:
pwd

'/Users/armcdona/Desktop/cms-workshop'

In [33]:
ls

Lesson 3.ipynb           data/                    functions_test.ipynb
THR4_ATP.png             data.zip                 geometry-analysis.ipynb
Untitled.ipynb           double_test.py
cms-workshop.ipynb       energies.txt


In [34]:
open_xyz('data/water.xyz')

(array(['O', 'H1', 'H2'], dtype='<U9'),
 array([[ 0.      , -0.007156,  0.965491],
        [-0.      ,  0.001486, -0.003471],
        [ 0.      ,  0.931026,  1.207929]]))

In [35]:
open_xyz('data/benzene.xyz')

(array(['C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H'],
       dtype='<U8'), array([[ 0.     ,  1.40272,  0.     ],
        [ 0.     ,  2.49029,  0.     ],
        [-1.21479,  0.70136,  0.     ],
        [-2.15666,  1.24515,  0.     ],
        [-1.21479, -0.70136,  0.     ],
        [-2.15666, -1.24515,  0.     ],
        [ 0.     , -1.40272,  0.     ],
        [ 0.     , -2.49029,  0.     ],
        [ 1.21479, -0.70136,  0.     ],
        [ 2.15666, -1.24515,  0.     ],
        [ 1.21479,  0.70136,  0.     ],
        [ 2.15666,  1.24515,  0.     ]]))

In [36]:
water_symbols, water_coordinates = open_xyz('data/water.xyz')

In [37]:
print(water_symbols)

['O' 'H1' 'H2']


In [38]:
print(water_coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [40]:
import numpy
import os

def open_xyz(filename):
    """
    Opens and processes a standard format xyz file.  Returns symbols and numpy array
    of coordinates.
    """
    xyz_file = numpy.genfromtxt(fname=filename, skip_header=2, dtype='unicode')
    symbols = xyz_file[:,0]
    coordinates = xyz_file[:,1:]
    coordinates = coordinates.astype(numpy.float)
    return symbols, coordinates

def bond_check(distance, mininum_length=0, maximum_length=1.5):
    """
    The function accepts a single distance (one number) and checks to see if it is between 
    the specificed minimum (default: 0 angstroms) and maximum values (default: 1.5 angtroms).  
    """
    if distance > mininum_length and distance < maximum_length:
        return True
    else:
        return False
    
def calculate_distance(atom1_coord, atom2_coord):
    """
    This function takes the coodinates of two atoms and calculates the distances between them.
    Inputs: atom1_coord, atom2_coord
    Return: distance
    """
    x_distance = atom1_coord[0]-atom2_coord[0]
    y_distance = atom1_coord[1]-atom2_coord[1]
    z_distance = atom1_coord[2]-atom2_coord[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance

file_location = os.path.join('data', 'water.xyz')
symbols, coord = open_xyz(file_location)
num_atoms = len(symbols)
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        if num1<num2:
            bond_length_12 = calculate_distance(coord[num1], coord[num2])
            if bond_check(bond_length_12) is True:
                print(F'{symbols[num1]} to {symbols[num2]}: {bond_length_12:.3f}')

O to H1: 0.969
O to H2: 0.969
